// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ODIn93rNu8ev57JnkEhn_WxFSheZ64E',
    appId: '1:80603576089:web:aa2397dfac96d12432b788',
    messagingSenderId: '80603576089',
    projectId: 'comfyfirebase',
    authDomain: 'comfyfirebase.firebaseapp.com',
    storageBucket: 'comfyfirebase.appspot.com',
    measurementId: 'G-M6D25HEVTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJD53f2jZ6evrKqHxmxXqkgkZD0FXF_I',
    appId: '1:80603576089:android:ce64812f64ab8ed432b788',
    messagingSenderId: '80603576089',
    projectId: 'comfyfirebase',
    storageBucket: 'comfyfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfYl9NmRDjru4O1swus_tnHvEOaoqSn0',
    appId: '1:80603576089:ios:22394a23db95671832b788',
    messagingSenderId: '80603576089',
    projectId: 'comfyfirebase',
    storageBucket: 'comfyfirebase.appspot.com',
    iosBundleId: 'com.example.feedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSfYl9NmRDjru4O1swus_tnHvEOaoqSn0',
    appId: '1:80603576089:ios:22394a23db95671832b788',
    messagingSenderId: '80603576089',
    projectId: 'comfyfirebase',
    storageBucket: 'comfyfirebase.appspot.com',
    iosBundleId: 'com.example.feedback',
  );
}
